### ISSUE TITLE
Update to Flow 0.4.0

### ISSUE THREAD

**Issue by danvk** [isuttell/grunt-flow-type-check#1]
Flow 0.4.0 was released a few days ago: http://flowtype.org/blog/2015/02/20/Flow-Comments.html

The built-in flow binary is at 0.2.0, and differences between the two are starting to become more apparent.

This mostly manifests itself when you run `grunt flow` on a Travis worker. So a reasonable alternative solution would be to document how to install an up-to-date version of Flow on Travis :)

**Comment by danvk** [comment]
Or get the latest version through https://www.npmjs.com/package/flow-bin

**Comment by danvk** [comment]
Here's a minimal change the runs `grunt-flow-type-check` using the latest `flow` binary on Travis-CI https://github.com/hammerlab/pileup.js/pull/8.

The gist is:

```
npm install --save-dev flow-bin
```

and then add `.*node_modules/flow-bin.*` to the `ignore` section of your `.flowconfig`.

**Comment by isuttell** [comment]
I'm working on a update which should be live today. The api changed a little so I have to update the task to accommodate those changes.
