### ISSUE TITLE
Swallows errors in .flowconfig

### ISSUE THREAD

**Issue by danvk** [isuttell/grunt-flow-type-check#2]
```
$ grunt flow
Running "flow:app" (flow) task
Warning: Task "flow:app" failed. Use --force to continue.

Aborted due to warnings.
```

on the other hand:

```
./node_modules/.bin/flow
Flow server launched for /Users/danvk/github/pileup.js
.flowconfig:14 Unable to parse line
Could not start flow server!
```

It would be very helpful if `grunt-flow-type-check` could surface the error about the `.flowconfig` file from the underlying `flow` process.

**Comment by isuttell** [comment]
I agree. I'll look into.

**Comment by isuttell** [comment]
Could you provide an example `.flowconfig` that won't parse. With the most recent version of flow the plugin is reporting flowconfig errors

```
Warning: .flowconfig:1 Unexpected config line not in any section
```
